apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-uat
  namespace: uat
spec:
  replicas: 3
  template:
    metadata:
      name: sample-app-uat
      labels:
        run: sample-app-uat
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: run
                      operator: In
                      values:
                        - springtestdev
                topologyKey: kubernetes.io/hostname
      containers:
        - name: sample-microservice
          image: registry.ng.bluemix.net/jason-test/sample_repo:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 1
      imagePullSecrets:
        - name: bluemix-uat-secret-regional


---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-uat
  labels:
    run: sample-app-uat
spec:
  selector:
    run: sample-app-uat
  ports:
   - protocol: TCP
     port: 8080
  type: LoadBalancer
