apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: sample-microservice
      image: registry.ng.bluemix.net/jason-test/sample_repo:latest
  imagePullSecrets:
    - name: dev-secret
